#!/usr/bin/env bash

TARGET_DIR="$HOME/arcanist/"
PATH_ENTRY="export PATH=\"\$PATH:$TARGET_DIR/arcanist/bin\""
PATH_CONFIGURED=`cat ~/.bashrc | grep export\ PATH\=\" | grep /arcanist/bin | wc -l`

sudo apt update
sudo apt install -y php7.0-cli php7.0-json php7.0-curl php7.0-common

if [[ $? -gt 0 ]]; then
    echo -e "\033[31mOnly Debian-based systems are supported!\033[39m"
    exit 1
fi

if [[ ! -d "$TARGET_DIR" ]]; then
    mkdir $TARGET_DIR
fi

pushd $TARGET_DIR

if [[ ! -d "$TARGET_DIR/libphutil" ]]; then
    git clone https://github.com/phacility/libphutil.git
fi

if [[ ! -d "$TARGET_DIR/arcanist" ]]; then
    git clone https://github.com/phacility/arcanist.git
fi

if [[ $PATH_CONFIGURED -eq 0 ]]; then
    echo $PATH_ENTRY >> ~/.bashrc
fi

popd

echo -e "\033[36mFinished setting up Arcanist!\033[39m"

echo -e "\033[36mInstalling certificate for p.cermati.com\033[39m"
$TARGET_DIR/arcanist/bin/arc install-certificate https://p.cermati.com
