#!/usr/bin/env bash
set -e
trap "exit" INT

sudo apt-get -y install expect unzip wget

mkdir -p .bin.cloud/

if [[ ! -f "./.bin.cloud/vault_1.1.0_linux_amd64.zip" ]]; then
    wget -P ./.bin.cloud/ https://releases.hashicorp.com/vault/1.1.0/vault_1.1.0_linux_amd64.zip
fi
unzip -o ./.bin.cloud/vault_1.1.0_linux_amd64.zip -d ./.bin.cloud/
chmod 755 ./.bin.cloud/vault

if [[ ! -f "./.bin.cloud/jq" ]]; then
    wget -O ./.bin.cloud/jq https://github.com/stedolan/jq/releases/download/jq-1.6/jq-linux64
    chmod 755 ./.bin.cloud/jq
fi

if [[ ! -f "./.bin.cloud/yq" ]]; then
    wget -O ./.bin.cloud/yq https://github.com/mikefarah/yq/releases/download/2.2.0/yq_linux_amd64
    chmod 755 ./.bin.cloud/yq
fi