#!/bin/bash
export TARGET=$1
export NAME=$2
if [[ $TARGET == "csr" ]]; then
    if [[ "$NAME" == "ca" ]]; then
        openssl req \
            -in csr/ca.csr \
            -noout \
            -text
    else
        openssl req \
            -in csr/$NAME.csr \
            -noout \
            -text
    fi
elif [[ $TARGET == "crt" ]]; then
    if [[ "$NAME" == "ca" ]]; then
        openssl x509 \
            -in ca.crt \
            -noout \
            -text
    else
        openssl x509 \
            -in certs/$NAME.crt \
            -noout \
            -text
    fi
elif [[ "$TARGET" == "crl" ]]; then
    openssl ca -config ./etc/ca.conf -gencrl -out ./ca.crl
    openssl crl -in ca.crl -noout -text
fi
