#!/usr/bin/env bash
set -e
trap "exit" INT

function vault-auth-cert-setup-validate {
    local clusterInventory=$1
    local blueprint=$2
    local inventoryFile=~/.host-inventory/inventory.d/${clusterInventory}
    local blueprintFile=./pki/blueprint/auth/cert/${clusterInventory}/${blueprint}/conf.yml

    if [[ ! -f "${inventoryFile}" ]]; then
        echo -e "${RED}[ERROR]${NC} ${YELLOW}${clusterInventory}${NC} cluster inventory not found. Expected on: ${RED}[${inventoryFile}]${NC}"
        echo -e "Try to run ${YELLOW}./pkictl inventory setup${NC} to setup inventories needed for pkictl"
        exit 1
    fi
    
    if [[ ! -f "${blueprintFile}" ]]; then
        echo -e "${RED}[ERROR]${NC} ${YELLOW}${blueprintFile}${NC} Certificate Auth blueprint file not found. Expected on: ${RED}[${blueprintFile}]${NC}"
        exit 1
    fi
}

function vault-auth-cert-setup-execute {
    local clusterInventory=$1
    local blueprint=$2
    local inventoryFile=~/.host-inventory/inventory.d/${clusterInventory}
    local currentDirectory=$(pwd)
    local blueprintFile=${currentDirectory}/pki/blueprint/auth/cert/${clusterInventory}/${blueprint}/conf.yml

    if [[ "${clusterInventory}" == "local" ]]; then
        echo -ne "${GREEN}[PKICTL]${NC} "
        $ANSIBLE_PLAYBOOK pki/playbook/pki-vault-auth-cert-setup.yml \
            -i "${inventoryFile}" \
            -e "cluster=${clusterInventory}" \
            -e "blueprint=${blueprint}" \
            -e "blueprint_file=${blueprintFile}" \
            --ask-become-pass
    else
        $ANSIBLE_PLAYBOOK pki/playbook/pki-vault-auth-cert-setup.yml \
            -i "${inventoryFile}" \
            -e "cluster=${clusterInventory}" \
            -e "blueprint=${blueprint}" \
            -e "blueprint_file=${blueprintFile}"
    fi
}

if [ $# == 0 ]; then
    exit 3
fi

if [[ " ${1} " == *"help"* ]] || [[ " ${1} " == *"--help"* ]];then
    exit 3
else
    if [[ -z "$1" ]] || [[ -z "$2" ]]; then
        exit 3
    else
        vault-auth-cert-setup-validate $1 $2
        vault-auth-cert-setup-execute $1 $2
    fi
fi