#!/bin/bash

set -e
trap "handle_shared_service_not_found" 1

build() {
  local SERVICE_NAME=$1
  local ENVIRONMENT=$2
  local BUILD_DIRECTORY=$3

  local SHARED_SCRIPTS_DIRECTORY=".services.d/shared"
  source ${SHARED_SCRIPTS_DIRECTORY}/build $1 $2 $3

  pushd ${BUILD_DIRECTORY}/upload
    sudo composer install
  popd
  sudo chown -R www-data ${BUILD_DIRECTORY}/upload
}

run() {
  local SERVICE_NAME=$1
  local ENVIRONMENT=$2
  local BUILD_DIRECTORY=$3

  local RED='\033[0;31m'
  local GREEN='\033[0;32m'
  local YELLOW='\033[1;33m'
  local NC='\033[0m' # No Color

  echo -e "${GREEN}[RUN]${NC} Starting NGINX"
  sudo service nginx start

  echo -e "${GREEN}[RUN]${NC} Running NodeJs worker..."
  sudo GITHUB_USERNAME=${GITHUB_USERNAME} node refresh-credential.js
}

handle_shared_service_not_found() {
  export RED='\033[0;31m'
  export NC='\033[0m' # No Color
  echo -e "${RED}[ERROR]${NC} Shared services directory not found"
  echo -e "${RED}[ERROR]${NC} Make sure that the scripts is run through svctl"

  exit 1
}
