#!/bin/bash
function namespace-help {
    echo -e "Namespace should be set properly as a file ${YELLOW}NAMESPACE.vars${NC} in ${YELLOW}blueprint${NC} folder."
    if [ ! -f "blueprint/NAMESPACE.vars" ]; then
        echo -e "- ${YELLOW}blueprint/NAMESPACE.vars${NC} ${RED}[FAILED]${NC}" 
    else
        echo -e "- ${YELLOW}blueprint/NAMESPACE.vars${NC} ${GREEN}[SUCCESS]${NC}"    
    fi
}

namespace-help