#!/usr/bin/env bash

set -e

source sv/app/.helper/common

echo ""
echo -e "Build a Docker image containing PKICTL service certificate, which" \
        "be used by Kubernetes to populate the service's container with" \
        "the service's PKICTL certificate." | fold -w 80 -s
echo ""
echo "Example:"
echo "  ./svctl pki build-initcontainer a_service an_env"
echo ""

svctl_run "pki.build_initcontainer" --help
