#!/bin/sh

build_plugin() {
  local RED='\033[0;31m'
  local GREEN='\033[0;32m'
  local YELLOW='\033[1;33m'
  local NC='\033[0m' # No Color

  local PLUGIN_NAME=$1
  local AUTOLOAD_DIR=$2

  local SOURCE_DIR=$PLUGIN_NAME
  local TARGET_DIR=".build/$PLUGIN_NAME"

  # Create target if not exist
  mkdir -p $TARGET_DIR

  # Replace plugin on target
  echo "${GREEN}[BUILD]${NC} Cleaning old files... ${YELLOW}(~15 seconds)${NC}"
  rm -rf $TARGET_DIR

  # Copy plugin from source to target
  cp -Lr "$SOURCE_DIR" "$TARGET_DIR"

  echo "${GREEN}[BUILD]${NC} Copying ${SOURCE_DIR} to ${TARGET_DIR} directory... ${YELLOW}(~30 seconds)${NC}"

  # Copy composer vendor dir to target plugin dir
  cp -Lr "$TARGET_DIR/vendor" "$TARGET_DIR/plugin/$AUTOLOAD_DIR"

  # Copy target plugin dir to CMS upload dir
  # Note: CMS upload dir might not exist during CI build
  if [ -d $TARGET_DIR/upload ]; then
    cp -Lr $TARGET_DIR/plugin/* $TARGET_DIR/upload

    # Release(WooCommerce): move contents of indodana-payment
    # directly under plugin dir before zipped
    if [ -z "${PLUGIN_NAME##woocommerce*}" ]; then
      mkdir $TARGET_DIR/temp
      cp -Lr $TARGET_DIR/plugin/wp-content/plugins/indodana-payment/* $TARGET_DIR/temp
      rm -rf $TARGET_DIR/plugin
      mv $TARGET_DIR/temp $TARGET_DIR/plugin
    fi
  fi
}
