#!/usr/bin/env bash
set -e
trap "exit" INT

function service-certs-distribute-validate {
    local CLUSTER_INVENTORY=$1
    local SERVICE_BLUEPRINT=$2
    local TARGET_HOST=$3
    local INVENTORY_FILE=~/.host-inventory/inventory.d/${CLUSTER_INVENTORY}
    local TEMP_DIRECTORY=.tmp.pki
    local CURRENT_DIRECTORY=$(pwd)
    local BLUEPRINT_FILE=${CURRENT_DIRECTORY}/pki/blueprint/certs/${CLUSTER_INVENTORY}/${SERVICE_BLUEPRINT}/spec.yml
    
    if [[ ! -d "${TEMP_DIRECTORY}" ]]; then
        mkdir -p .tmp.pki
    fi

    if [[ ! -f "${INVENTORY_FILE}" ]]; then
        echo -e "${RED}[ERROR]${NC} ${YELLOW}${CLUSTER_INVENTORY}${NC} cluster inventory not found. Expected on: ${RED}[${INVENTORY_FILE}]${NC}"
        echo -e "Try to run ${YELLOW}./pkictl inventory setup${NC} to setup inventories needed for pkictl"
        exit 1
    fi

    if [[ ! -f "${BLUEPRINT_FILE}" ]]; then
        echo -e "${RED}[ERROR]${NC} ${YELLOW}${BLUEPRINT_FILE}${NC} blueprint file not found. Expected on: ${RED}[${BLUEPRINT_FILE}]${NC}"
        exit 1
    fi
}


function service-certs-distribute-execute {
    local CLUSTER_INVENTORY=$1
    local SERVICE_BLUEPRINT=$2
    local TARGET_HOST=$3
    local INVENTORY_FILE=~/.host-inventory/inventory.d/${CLUSTER_INVENTORY}
    local CURRENT_DIRECTORY=$(pwd)
    local TEMP_DIRECTORY=${CURRENT_DIRECTORY}/.tmp.pki
    local BLUEPRINT_FILE=${CURRENT_DIRECTORY}/pki/blueprint/certs/${CLUSTER_INVENTORY}/${SERVICE_BLUEPRINT}/spec.yml
    local PKI_DIRECTORY=/usr/share/pki

    if [[ "${CLUSTER_INVENTORY}" == "local" ]]; then
        echo -ne "${GREEN}[PKICTL]${NC} Certificates are ready to use in ${YELLOW}/usr/share/pki/certs/service/${SERVICE_BLUEPRINT}${NC}. You don't need to run distribute script."
    else
        $ANSIBLE_PLAYBOOK pki/playbook/pki-service-certs-distribute.yml \
            -i "${INVENTORY_FILE}" \
            -e "blueprint=${SERVICE_BLUEPRINT}" \
            -e "blueprint_file=${BLUEPRINT_FILE}" \
            -e "target_service=${TARGET_HOST}" \
            -e "cluster=${CLUSTER_INVENTORY}" \
            -e "tmp_dir=${TEMP_DIRECTORY}" \
            -e "pki_dir=${PKI_DIRECTORY}"

        echo -e "${GREEN}[PKICTL]${NC} Cleaning up temporary files..."
        rm -rf ${TEMP_DIRECTORY}/*
    fi
}

if [ $# == 0 ]; then
    exit 3
fi

if [[ " ${1} " == *"help"* ]] || [[ " ${1} " == *"--help"* ]];then
    exit 3
else
    if [[ -z "$1" ]] || [[ -z "$2" ]] || [[ -z "$3" ]]; then
        exit 3
    else
        service-certs-distribute-validate $1 $2 $3
        service-certs-distribute-execute $1 $2 $3
    fi
fi