#!/usr/bin/env bash

YOUR_SUDO_PASS=""

function service-certs-issue-validate {
    local CLUSTER_INVENTORY=$1
    local SERVICE_BLUEPRINT=$2
    local TARGET_CA=$3
    local INVENTORY_FILE=~/.host-inventory/inventory.d/${CLUSTER_INVENTORY}
    
    if [[ ! -f "${INVENTORY_FILE}" ]]; then
        echo -e "${RED}[ERROR]${NC} ${YELLOW}${CLUSTER_INVENTORY}${NC} cluster inventory not found. Expected on: ${RED}[${INVENTORY_FILE}]${NC}"
        echo -e "Try to run ${YELLOW}./pkictl inventory setup${NC} to setup inventories needed for pkictl"
        exit 1
    fi
}

function service-certs-issue-execute {
    local CLUSTER_INVENTORY=$1
    local SERVICE_BLUEPRINT=$2
    local TARGET_CA=$3
    local INVENTORY_FILE=~/.host-inventory/inventory.d/${CLUSTER_INVENTORY}
    local TOOLKIT_DIRECTORY=/usr/share/pki
    local CURRENT_DIRECTORY=$(pwd)
    local VAULT_PASSWORD_FILE=${CURRENT_DIRECTORY}/vault_password.txt

    if [[ "${CLUSTER_INVENTORY}" == "local" ]]; then
        $ANSIBLE_PLAYBOOK pki/playbook/pki-service-certs-issue.yml \
            -i "${INVENTORY_FILE}" \
            -e "blueprint=${SERVICE_BLUEPRINT}" \
            -e "cluster=${CLUSTER_INVENTORY}" \
            -e "target_ca=${TARGET_CA}" \
            -e "toolkit_directory=${TOOLKIT_DIRECTORY}" \
            -e "ansible_sudo_pass=${YOUR_SUDO_PASS}"
    else
        $ANSIBLE_PLAYBOOK pki/playbook/pki-service-certs-issue.yml \
            -i "${INVENTORY_FILE}" \
            -e "blueprint=${SERVICE_BLUEPRINT}" \
            -e "cluster=${CLUSTER_INVENTORY}" \
            -e "target_ca=${TARGET_CA}" \
            -e "toolkit_directory=${TOOLKIT_DIRECTORY}" \
            --vault-password-file "${VAULT_PASSWORD_FILE}"
    fi
}

if [ $# == 0 ]; then
    exit 3
fi

if [[ " ${1} " == *"help"* ]] || [[ " ${1} " == *"--help"* ]];then
    exit 3
else
    if [[ -z "$1" ]] || [[ -z "$2" ]] || [[ -z "$3" ]]; then
        exit 3
    else
        service-certs-issue-validate $1 $2 $3

        if [[ "${1}" == "local" ]]; then
            echo -ne "${GREEN}[PKICTL]${NC} SUDO password: "
            read -s YOUR_SUDO_PASS
            echo -e "\n"
        fi

        service-certs-issue-execute $1 $2 $3
    fi
fi