#!/usr/bin/env bash
if [[ ! -d ".env.db" ]]; then
    python3 -m venv .env.db
    source .env.db/bin/activate
    pip install ansible==2.7.7.0
fi
source .env.db/bin/activate

export ANSIBLE_PLAYBOOK=./.env.db/bin/ansible-playbook
export ANSIBLE_INVALID_TASK_ATTRIBUTE_FAILED=false
export SILENT_OPT="--silent"

source db/framework/complete
source db/framework/help
source db/framework/utils
source db/framework/cli

cli "$@"
