#!/usr/bin/env bash
if [[ ! -d ".env.pki" ]]; then
    sudo apt-get -y install virtualenv
    virtualenv .env.pki
    source .env.pki/bin/activate
    pip install ansible==2.7.7.0
fi
source .env.pki/bin/activate

export ANSIBLE_PLAYBOOK=./.env.pki/bin/ansible-playbook

source pki/framework/cli
source pki/framework/complete
source pki/framework/help
source pki/framework/utils
cli "$@"