#!/usr/bin/env bash

source sv/framework/utils
source sv/app/.helper/common

if [[ $(svctl_binary_check) = 'SOURCE' ]]; then
  # Setup Python 3.7
  if [[ ! -f /usr/bin/python3.7 ]]; then
    sudo add-apt-repository ppa:deadsnakes/ppa -y
    sudp apt-get update
    sudo apt-get install -y python 3.7 python3.7-dev
  fi

  # Setup virtualenv
  if [[ ! -f .env.sv/bin/activate ]]; then
    if ! which virtualenv; then
      logger_warn "Python virtualenv is not installed, will be installed now"
      logger_warn "Executing ${COLOR_YELLOW}sudo apt-get install virtualenv${COLOR_NORMAL}..."

      sudo apt-get install virtualenv
    fi

    logger_info "Setting up virtualenv..."
    virtualenv --python "$(which python3.7)" .env.sv
  fi

  source .env.sv/bin/activate

  # Reinstall Python dependencies when the requirements.txt changed
  if [[ ! -f .env.sv/requirements.installed ]] || ! cmp --quiet .env.sv/requirements.installed sv/requirements.txt; then
    logger_info "Updating Python dependencies..."

    pip install -r sv/requirements.txt
    echo "--------------------------------------------------------------------------------"
    echo ""

    cp sv/requirements.txt .env.sv/requirements.installed
  fi

  logger_warn "Executing svctl from source instead of compiled binary. Some" \
    "commands might fail."
fi

source sv/framework/cli
source sv/framework/complete
source sv/framework/help

cli "$@"
