#!/usr/bin/env bash

set -e

source sv/app/.helper/common

# Check for system-wide installation of kubectl. Append $HOME/.local/bin to PATH
# if kubectl is not found to be checked again
if ! which kubectl > /dev/null; then
  export PATH="${HOME}/.local/bin:${PATH}"
fi

# Install local kubectl in $HOME/.local/bin if it is still not found
if ! which kubectl > /dev/null; then
  logger_warn "${COLOR_YELLOW}kubectl${COLOR_NORMAL} is not installed." \
    "Will be installed as ${COLOR_YELLOW}${HOME}/.local/bin/kubectl${COLOR_NORMAL}"

  mkdir -p "${HOME}/.local/bin"

  latest_version=$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)

  curl --silent "https://storage.googleapis.com/kubernetes-release/release/$latest_version/bin/linux/amd64/kubectl" \
    -o "${HOME}/.local/bin/kubectl"

  chmod +x "${HOME}/.local/bin/kubectl"

  logger_info "${COLOR_YELLOW}kubectl ${latest_version}${COLOR_NORMAL} installed"
fi

svctl_run "kubernetes.deploy" "$@"
