#!/bin/bash

set -e
trap "handle_shared_service_not_found" 1

build() {
  local SHARED_SCRIPTS_DIRECTORY=".services.d/shared"
  source ${SHARED_SCRIPTS_DIRECTORY}/build $1 $2 $3
}

run() {
  local SERVICE_NAME=$1
  local ENVIRONMENT=$2
  local BUILD_DIRECTORY=$3
  local HOST=$4
  local PORT=$5

  NGINX_PORT=$PORT
  if [[ -z $5 ]]; then
    NGINX_PORT="80"
  fi

  if [[ -z $4 ]]; then
    HOST="localhost"
  fi
  
  local RED='\033[0;31m'
  local GREEN='\033[0;32m'
  local YELLOW='\033[1;33m'
  local NC='\033[0m' # No Color

  echo -e "${GREEN}[RUN]${NC} Starting NGINX"
  NODE=$(which node)
  sudo HOST=${HOST} PORT=${NGINX_PORT} ${NODE} generate-nginx-config.js

  NPX=$(which npx)
  echo "$PORT";
  echo -e "${GREEN}[RUN]${NC} Running NodeJs worker..."
  sudo GITHUB_USERNAME=${GITHUB_USERNAME} \
    ENVIRONMENT=${ENVIRONMENT} \
    HOST=${HOST} \
    PORT=${PORT} \
    ${NPX} forever -o logs/out.log -e logs/err.log -a start refresh-credential.js
}

handle_shared_service_not_found() {
  export RED='\033[0;31m'
  export NC='\033[0m' # No Color
  echo -e "${RED}[ERROR]${NC} Shared services directory not found"
  echo -e "${RED}[ERROR]${NC} Make sure that the scripts is run through svctl"

  exit 1
}