#!/bin/bash
export NAME=$1

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

function help {
    echo -e "Usage: ./sign {NAME}"
    echo -e "${YELLOW}NAME${NC} should be Linux compatible file name format."
    echo -e "The command will read file using supplied NAME in ./csr folder."
}

if [[ -z "$NAME" ]]; then
    help
    exit
fi

if [[ ! -f "csr/$NAME.csr" ]]; then
    echo -e "File ${RED}csr/${NAME}.csr${NC} does not exist. Please verify whether the CSR has been initiated successfully."
    exit
fi

export SERIAL=$(cat .db/ca.crt.srl)

openssl ca -batch \
    -config etc/ca.conf \
    -in csr/${NAME}.csr \
    -out certs/${NAME}.crt \
    -extensions intermediate_ca_ext