#!/usr/bin/env bash
set -e
trap "exit" INT

function vault-secrets-db-setup-validate {
    local clusterInventory=$1
    local blueprint=$2
    local dbGroup=$3
    local inventoryFile=~/.host-inventory/inventory.d/${clusterInventory}
    local secretsBlueprintFile=./pki/blueprint/secrets/db/${clusterInventory}/${blueprint}/${dbGroup}/conf.yml
    local statementsDirectory=./pki/files/secrets/db/${clusterInventory}/${blueprint}/${dbGroup}

    if [[ ! -f "${inventoryFile}" ]]; then
        echo -e "${RED}[ERROR]${NC} ${YELLOW}${clusterInventory}${NC} cluster inventory not found. Expected on: ${RED}[${inventoryFile}]${NC}"
        echo -e "Try to run ${YELLOW}./pkictl inventory setup${NC} to setup inventories needed for pkictl"
        exit 1
    fi
    
    if [[ ! -f "${secretsBlueprintFile}" ]]; then
        echo -e "${RED}[ERROR]${NC} ${YELLOW}${secretsBlueprintFile}${NC} database secrets blueprint file not found. Expected on: ${RED}[${secretsBlueprintFile}]${NC}"
        exit 1
    fi

    if [[ ! -d "${statementsDirectory}" ]]; then
        echo -e "${RED}[ERROR]${NC} ${YELLOW}${statementsDirectory}${NC} temporary credentials SQL statements directory not found. Expected on: ${RED}[${statementsDirectory}]${NC}"
        exit 1
    fi
}

function vault-secrets-db-setup-execute {
    local clusterInventory=$1
    local blueprint=$2
    local dbGroup=$3
    local inventoryFile=~/.host-inventory/inventory.d/${clusterInventory}
    local currentDirectory=$(pwd)
    local secretsBlueprintFile=${currentDirectory}/pki/blueprint/secrets/db/${clusterInventory}/${blueprint}/${dbGroup}/conf.yml
    local statementsDirectory=${currentDirectory}/pki/files/secrets/db/${clusterInventory}/${blueprint}/${dbGroup}

    if [[ "${clusterInventory}" == "local" ]]; then
        echo -ne "${GREEN}[PKICTL]${NC} "
        $ANSIBLE_PLAYBOOK pki/playbook/pki-vault-db-setup.yml \
            -i "${inventoryFile}" \
            -e "cluster=${clusterInventory}" \
            -e "blueprint=${blueprint}" \
            -e "blueprint_file=${secretsBlueprintFile}" \
            -e "statements_directory=${statementsDirectory}" \
            -e "db_group=${dbGroup}" \
            --ask-become-pass
    else
        $ANSIBLE_PLAYBOOK pki/playbook/pki-vault-db-setup.yml \
            -i "${inventoryFile}" \
            -e "cluster=${clusterInventory}" \
            -e "blueprint=${blueprint}" \
            -e "blueprint_file=${secretsBlueprintFile}" \
            -e "creation_statements_directory=${creationStatementsDirectory}"
    fi
}

if [ $# == 0 ]; then
    exit 3
fi

if [[ " ${1} " == *"help"* ]] || [[ " ${1} " == *"--help"* ]];then
    exit 3
else
    if [[ -z "$1" ]] || [[ -z "$2" ]] || [[ -z "$3" ]]; then
        exit 3
    else
        vault-secrets-db-setup-validate $1 $2 $3
        vault-secrets-db-setup-execute $1 $2 $3
    fi
fi