#!/usr/bin/env bash
function pki-init-local-help {
    echo -e ""
    echo -e "Initialize local Public Key Infrastructure"
    echo -e "${RED}BEWARE THIS COMMAND WILL CLEAN-UP AND RE-INITIALIZE THE WHOLE CERTIFICATE AUTHORITY${NC}"
    echo -e "${RED}PLEASE TAKE EXTRA CAUTION WHEN INVOKING THIS COMMAND.${NC}"
    echo -e "${RED}PLEASE ONLY USE THIS FOR LOCAL / DEVELOPMENT ENVIRONMENT ONLY.${NC}"
    echo -e "${YELLOW}Usage:${NC} ${GREEN}./pkictl${NC} pki init local"
}

pki-init-local-help