#!/usr/bin/env bash
set -e
trap "exit" INT

function pki-init-local-validate {
    local INVENTORY_FILE=~/.host-inventory/inventory.d/local
    local PKICTL_DIRECTORY=/usr/share/pki
    local CURRENT_DIRECTORY=$(pwd)
    local PKI_TEMPLATE_DIRECTORY=${CURRENT_DIRECTORY}/pki/files/pki-template/local-ca
    local PKI_TOOLKIT_DIRECTORY=${CURRENT_DIRECTORY}/pki/files/pki-toolkit-template

    if [[ ! -f "${INVENTORY_FILE}" ]]; then
        echo -e "${RED}[ERROR]${NC} ${YELLOW}${CLUSTER_INVENTORY}${NC} cluster inventory not found. Expected on: ${RED}[${INVENTORY_FILE}]${NC}"
        echo -e "Try to run ${YELLOW}./pkictl inventory setup${NC} to setup inventories needed for pkictl"
        exit 1
    fi
    
    if [[ ! -d "${PKI_TEMPLATE_DIRECTORY}" ]]; then
        echo -e "${RED}[ERROR]${NC} ${YELLOW}${clusterInventory}${NC} PKI template directory not found. Expected on: ${RED}[${PKI_TEMPLATE_DIRECTORY}]${NC}"
        exit 1
    fi

    if [[ ! -d "${PKI_TOOLKIT_DIRECTORY}" ]]; then
        echo -e "${RED}[ERROR]${NC} ${YELLOW}${clusterInventory}${NC} PKI toolkit not found. Expected on: ${RED}[${PKI_TOOLKIT_DIRECTORY}]${NC}"
        exit 1
    fi
}

function pki-init-local-execute {
    local INVENTORY_FILE=~/.host-inventory/inventory.d/local
    local PKICTL_DIRECTORY=/usr/share/pki
    local CURRENT_DIRECTORY=$(pwd)
    local PKI_TEMPLATE_DIRECTORY=${CURRENT_DIRECTORY}/pki/files/pki-template/local-ca
    local PKI_TOOLKIT_DIRECTORY=${CURRENT_DIRECTORY}/pki/files/pki-toolkit-template

    echo -ne "${GREEN}[PKICTL]${NC} "
    $ANSIBLE_PLAYBOOK pki/playbook/pki-local-init.yml \
        -i "${INVENTORY_FILE}" \
        -e "ca_server=local-ca" \
        -e "pkictl_directory=${PKICTL_DIRECTORY}" \
        -e "pki_template_directory=${PKI_TEMPLATE_DIRECTORY}" \
        -e "pki_toolkit_directory=${PKI_TOOLKIT_DIRECTORY}" \
        --ask-become-pass
}

if [[ " ${1} " == *"help"* ]] || [[ " ${1} " == *"--help"* ]];then
    exit 3
else
    echo -e ""
    echo -e "${RED}BEWARE THIS COMMAND WILL CLEAN-UP AND RE-INITIALIZE THE WHOLE CERTIFICATE AUTHORITY in path: /usr/share/pki/pki${NC}"
    echo -e "${RED}PLEASE TAKE EXTRA CAUTION WHEN INVOKING THIS COMMAND.${NC}"
    echo -e "${RED}PLEASE ONLY USE THIS FOR LOCAL / DEVELOPMENT ENVIRONMENT ONLY.${NC}"
    read -p "Are you sure (Y/y) for continuing? " -r
    echo -e ""
    if [[ $REPLY =~ ^[Yy]$ ]]
    then
        pki-init-local-validate
        pki-init-local-execute
    fi
fi