#!/usr/bin/env bash

function vault-secrets-ssh-distribute-validate {
    local clusterInventory=$1
    local blueprint=$2
    local hostGroupTarget=$3
    local inventoryFile=~/.host-inventory/inventory.d/${clusterInventory}
    local tempDirectory=.tmp.pki
    
    if [[ ! -d "${tempDirectory}" ]]; then
        mkdir -p .tmp.pki
    fi

    if [[ ! -f "${inventoryFile}" ]]; then
        echo -e "${RED}[ERROR]${NC} ${YELLOW}${clusterInventory}${NC} cluster inventory not found. Expected on: ${RED}[${inventoryFile}]${NC}"
        echo -e "Try to run ${YELLOW}./pkictl inventory setup${NC} to setup inventories needed for pkictl"
        exit 1
    fi
}

function vault-secrets-ssh-distribute-execute {
    local clusterInventory=$1
    local blueprint=$2
    local hostGroupTarget=$3
    local inventoryFile=~/.host-inventory/inventory.d/${clusterInventory}
    local currentDirectory=$(pwd)
    local tempDirectory=${currentDirectory}/.tmp.pki
    local secretsBlueprintFile=${currentDirectory}/pki/blueprint/secrets/ssh/${clusterInventory}/${blueprint}/${hostGroupTarget}/conf.yml

    $ANSIBLE_PLAYBOOK pki/playbook/pki-vault-ssh-distribute.yml \
        -i "${inventoryFile}" \
        -e "blueprint=${vaultBlueprint}" \
        -e "blueprint_file=${secretsBlueprintFile}" \
        -e "host_group_target=${hostGroupTarget}" \
        -e "temp_dir=${tempDirectory}"
}

if [ $# == 0 ]; then
    exit 3
fi

if [[ " ${1} " == *"help"* ]] || [[ " ${1} " == *"--help"* ]];then
    exit 3
else
    if [[ -z "$1" ]] || [[ -z "$2" ]] || [[ -z "$3" ]]; then
        exit 3
    else
        vault-secrets-ssh-distribute-validate $1 $2 $3
        vault-secrets-ssh-distribute-execute $1 $2 $3
    fi
fi