#!/bin/bash
function meta-help {
    echo -e "Meta should be set properly as a file ${YELLOW}dbctl.meta.vars${NC} in ${YELLOW}blueprint${NC} folder."
    if [ ! -f "blueprint/infra-devops/joker/dbctl-scripts/dbctl.meta.vars" ]; then
        echo -e "- ${YELLOW}blueprint/infra-devops/joker/dbctl-scripts/dbctl.meta.vars${NC} ${RED}[FAILED]${NC}" 
    else
        echo -e "- ${YELLOW}blueprint/infra-devops/joker/dbctl-scripts/dbctl.meta.vars${NC} ${GREEN}[SUCCESS]${NC}"    
    fi
}

meta-help