#!/bin/bash

set -e
trap "handle_shared_service_not_found" 1

build() {
  SERVICE_NAME=$1
  BUILD_DIRECTORY=$3

  pushd ${BUILD_DIRECTORY}
    sudo rm -rf plugin
  popd

  local SHARED_SCRIPTS_DIRECTORY=".services.d/shared"
  source ${SHARED_SCRIPTS_DIRECTORY}/build $1 $2 $3

  pushd ${SERVICE_NAME}/plugin
    sudo cp * -r ../../${BUILD_DIRECTORY}/upload
  popd
}

run() {
  local SERVICE_NAME=$1
  local ENVIRONMENT=$2
  local BUILD_DIRECTORY=$3
  local HOST=$4
  local PORT=$5

  if [[ -z $4 ]] && [[ -z $5 ]]; then
    HOST="localhost"
    PORT="6101"
  fi

  cd upload;

  php5.6 -S "$HOST:$PORT"
}

handle_shared_service_not_found() {
  export RED='\033[0;31m'
  export NC='\033[0m' # No Color
  echo -e "${RED}[ERROR]${NC} Shared services directory not found"
  echo -e "${RED}[ERROR]${NC} Make sure that the scripts is run through svctl"

  exit 1
}
