#!/bin/bash
mkdir -p .private .db .crl csr .certs certs
chmod 700 .private

cp /dev/null .db/ca.db
cp /dev/null .db/ca.db.attr

echo 10 > .db/ca.crt.srl
echo 10 > .db/ca.crl.srl

# Requesting Root CA using etc/ca.conf
# Outputting --> ca.csr (Certificate Signing Request), ca.key (private key)
# -nodes to disable pass-phrase
openssl req -new -nodes \
    -config etc/ca.conf \
    -out csr/ca.csr \
    -keyout .private/ca.key

# Self-Sign the Root CA using etc/ca.conf (extensions root_ca_ext)
# https://stackoverflow.com/questions/15476479/sign-certificate-without-prompt-in-shell-script
# Add -batch to skip prompt
openssl ca -selfsign -batch \
    -config etc/ca.conf \
    -in csr/ca.csr \
    -out ca.crt \
    -extensions root_ca_ext

cp ca.crt certs/ca.crt

rm ./init