#!/usr/bin/env bash

set -e

source sv/app/.helper/common

# Check for system-wide installation of kubectl
if ! which kubectl > /dev/null; then
  logger_warn "${COLOR_YELLOW}kubectl${COLOR_NORMAL} is not installed." \
    "Will be installed into ${COLOR_YELLOW}/usr/local/bin/kubectl${COLOR_NORMAL}"

  local latest_version=$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)

  curl --silent "https://storage.googleapis.com/kubernetes-release/release/$latest_version/bin/linux/amd64/kubectl" \
    -o /tmp/kubectl

  sudo mv /tmp/kubectl /usr/local/bin/kubectl
  chmod +x /usr/local/bin/kubectl

  mkdir -p "$HOME/.kube"

  logger_info "${COLOR_YELLOW}kubectl ${latest_version}${COLOR_NORMAL} installed"
fi

# Populate ~/.kube/config
if [ ! -f "$HOME/.kube/config" ] || [ ! -s "$HOME/.kube/config" ]; then
  logger_info "Creating initial ${COLOR_YELLOW}$HOME/.kube/config${COLOR_NORMAL}..."

  echo "apiVersion: v1
kind: Config
preferences: {}

clusters: []
users: []
contexts: []" > "$HOME/.kube/config"
fi

svctl_run "kubernetes.context.login" "$@"
