#!/bin/bash

set -e
trap "handle_shared_service_not_found" 1

build() {
  local -r PROJECT_DIR=$(pwd)
  local -r SERVICE_NAME=$1
  local -r ENVIRONMENT=$2
  local -r BUILD_DIR="$PROJECT_DIR/$3"
  local -r SERVICE_SOURCE_DIR="$PROJECT_DIR/$SERVICE_NAME"
  local -r SERVICE_BUILD_DIR="$BUILD_DIR/$SERVICE_NAME"

  rm -rf "$SERVICE_BUILD_DIR/plugin"

  local SHARED_SCRIPTS_DIRECTORY=".services.d/shared"
  source ${SHARED_SCRIPTS_DIRECTORY}/build

  # Copy composer vendor/ dir to plugin dir
  cp -Lr $SERVICE_SOURCE_DIR/vendor $SERVICE_BUILD_DIR/plugin/system/library/indodana

  # Copy plugin dir to CMS upload dir (register the plugin automatically)
  cp -Lr $SERVICE_BUILD_DIR/plugin/* $SERVICE_BUILD_DIR/upload
}

run() {
  local SERVICE_NAME=$1
  local ENVIRONMENT=$2
  local BUILD_DIRECTORY=$3
  local HOST=$4
  local PORT=$5

  if [[ -z $4 ]] && [[ -z $5 ]]; then
    HOST="localhost"
    PORT="6102"
  fi

  cd upload;

  php5.6 -S "$HOST:$PORT"
}
