#!/bin/bash

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'
export CURRENT_DIRECTORY=$(pwd)
echo $CURRENT_DIRECTORY
pushd $CURRENT_DIRECTORY/root-ca
echo -e "${GREEN}[PKI-BOOTSTRAP]${NC} Bootstrapping root-ca"
./init
popd

pushd $CURRENT_DIRECTORY/intermediate-ca
echo -e "${GREEN}[PKI-BOOTSTRAP]${NC} Bootstrapping intermediate-ca"
./init
popd

echo -e "${GREEN}[PKI-BOOTSTRAP]${NC} Sending intermediate-ca.csr"
cp $CURRENT_DIRECTORY/intermediate-ca/csr/ca.csr $CURRENT_DIRECTORY/root-ca/csr/intermediate-ca.csr

pushd $CURRENT_DIRECTORY/root-ca
echo -e "${GREEN}[PKI-BOOTSTRAP]${NC} Signing intermediate-ca.csr"
./sign intermediate-ca
popd

echo -e "${GREEN}[PKI-BOOTSTRAP]${NC} Sending intermediate-ca.crt and chaining the Root CA"
cp $CURRENT_DIRECTORY/root-ca/certs/intermediate-ca.crt intermediate-ca/ca.crt
cat ${CURRENT_DIRECTORY}/root-ca/certs/intermediate-ca.crt \
        ${CURRENT_DIRECTORY}/root-ca/ca.crt > intermediate-ca/ca-chain.crt

rm $CURRENT_DIRECTORY/bootstrap