#!/bin/bash
VAULT_EXEC=./.bin.db/vault

export VAULT_ADDR="https://localhost:8200"
export VAULT_CACERT=/usr/share/pki/certs/member/gerywahyu@03827496b46046e58700703488dd81aa@dbctl-dev/gerywahyu@03827496b46046e58700703488dd81aa@dbctl-dev.ca.crt
export VAULT_CLIENT_CERT=/usr/share/pki/certs/member/gerywahyu@03827496b46046e58700703488dd81aa@dbctl-dev/gerywahyu@03827496b46046e58700703488dd81aa@dbctl-dev.crt
export VAULT_CLIENT_KEY=/usr/share/pki/certs/member/gerywahyu@03827496b46046e58700703488dd81aa@dbctl-dev/.private/gerywahyu@03827496b46046e58700703488dd81aa@dbctl-dev.key
export VAULT_TOKEN=s.5N0b0qunuTtURp3qZHTotQAj

CURRENT_DIRECTORY=$(pwd)
mkdir -p $CURRENT_DIRECTORY/.credentials
CREDENTIAL_FILE=$CURRENT_DIRECTORY/.credentials/app.yaml

# v11-alt read - for Vault > 1.1.0
# echo "==> v11-alt read - for Vault > 1.1.0"
# $VAULT_EXEC read -format=yaml v1.1/cermati/indodana/db/hosted/mysql/testenv/woocommerce/dev/creds/app > $CREDENTIAL_FILE

# v11-read - for Vault > 1.1.0
echo "==> v11-read - for Vault > 1.1.0"
$VAULT_EXEC read -format=yaml v1.1/cermati/indodana/db/hosted/mysql/testenv/woocommerce/dev/creds/app > $CREDENTIAL_FILE

# v10-read - for Vault < 1.1.0
# echo "==> v10-read - for Vault < 1.1.0"
# $VAULT_EXEC read -format=yaml v10/cermati/indodana/db/hosted/mysql/creds/dev/testenv/woocommerce-migrations > $CREDENTIAL_FILE

cat $CREDENTIAL_FILE
