#!/bin/bash
VAULT_EXEC=./.bin.db/vault

export VAULT_ADDR="https://localhost:8200"
export VAULT_CACERT=/usr/share/pki/certs/member/gerywahyu@03827496b46046e58700703488dd81aa@dbctl-dev/gerywahyu@03827496b46046e58700703488dd81aa@dbctl-dev.ca.crt
export VAULT_CLIENT_CERT=/usr/share/pki/certs/member/gerywahyu@03827496b46046e58700703488dd81aa@dbctl-dev/gerywahyu@03827496b46046e58700703488dd81aa@dbctl-dev.crt
export VAULT_CLIENT_KEY=/usr/share/pki/certs/member/gerywahyu@03827496b46046e58700703488dd81aa@dbctl-dev/.private/gerywahyu@03827496b46046e58700703488dd81aa@dbctl-dev.key
export VAULT_TOKEN=s.dWFlypwNdKCI7bbb26wsCuEJ

echo "[DBCTL] Generating role configuration script for database/role/configure using DB v1.1/cermati/indodana/db/hosted/mysql/testenv/woocommerce/dev/config/root"

# v11-alt write - for Vault > 1.1.0
# echo "==> v11-alt write - for Vault > 1.1.0"
# $VAULT_EXEC write v1.1/cermati/indodana/db/hosted/mysql/testenv/woocommerce/dev/roles/app \
#  db_name=root \
#  creation_statements=@"/home/gwahyu/Developments/test-env/cli/db/blueprint/mysql/woocommerce/__roles__/dev/app/creation.sql" \
#    default_ttl="1h" \
#    max_ttl="24h"

# v11 write - for Vault > 1.1.0
# echo "==> v11 write - for Vault > 1.1.0"
$VAULT_EXEC write v1.1/cermati/indodana/db/hosted/mysql/testenv/woocommerce/dev/roles/app \
  db_name=root \
  creation_statements=@"/home/gwahyu/Developments/test-env/cli/db/blueprint/mysql/woocommerce/__roles__/dev/app/creation.sql" \
    default_ttl="1h" \
    max_ttl="24h"

# v10 write - for Vault < 1.1.0
# echo "==> v10 write - for Vault < 1.1.0"
# $VAULT_EXEC write v10/cermati/indodana/db/hosted/mysql/roles/dev/testenv/woocommerce-app \
#  db_name=dev/testenv/woocommerce \
#  creation_statements=@"/home/gwahyu/Developments/test-env/cli/db/blueprint/mysql/woocommerce/__roles__/dev/app/creation.sql" \
#    default_ttl="1h" \
#    max_ttl="24h"
