#!/usr/bin/env bash
set -e
trap "exit" INT

./pkictl inventory setup

./pkictl pki init local

echo -ne "\n${GREEN}[PKICTL]${NC} Enter your SUDO password to auto-authorize service certificates bootstrapping: "
read -s YOUR_SUDO_PASS
echo -e "\n"

echo "${YOUR_SUDO_PASS}" | ./pkictl service certs request local etcd-01-dev
echo "${YOUR_SUDO_PASS}" | ./pkictl service certs request local etcd-02-dev
echo "${YOUR_SUDO_PASS}" | ./pkictl service certs request local etcd-03-dev
echo "${YOUR_SUDO_PASS}" | ./pkictl service certs request local etcd-client-dev
echo "${YOUR_SUDO_PASS}" | ./pkictl service certs request local vault-01-dev
echo "${YOUR_SUDO_PASS}" | ./pkictl service certs request local vault-02-dev
echo "${YOUR_SUDO_PASS}" | ./pkictl service certs request local vault-client-dev
echo "${YOUR_SUDO_PASS}" | ./pkictl service certs request local vault-etcd-client-dev

echo "${YOUR_SUDO_PASS}" | ./pkictl service certs issue local etcd-01-dev intermediate-ca
echo "${YOUR_SUDO_PASS}" | ./pkictl service certs issue local etcd-02-dev intermediate-ca
echo "${YOUR_SUDO_PASS}" | ./pkictl service certs issue local etcd-03-dev intermediate-ca
echo "${YOUR_SUDO_PASS}" | ./pkictl service certs issue local etcd-client-dev intermediate-ca
echo "${YOUR_SUDO_PASS}" | ./pkictl service certs issue local vault-01-dev intermediate-ca
echo "${YOUR_SUDO_PASS}" | ./pkictl service certs issue local vault-02-dev intermediate-ca
echo "${YOUR_SUDO_PASS}" | ./pkictl service certs issue local vault-client-dev intermediate-ca
echo "${YOUR_SUDO_PASS}" | ./pkictl service certs issue local vault-etcd-client-dev intermediate-ca

./pkictl etcd deploy local local-etcd
./pkictl vault deploy local local-vault
./pkictl vault init local local-vault