#!/bin/bash
if [[ "$OS" == "Mac" ]]; then
    brew install postgresql@9.6
    brew install postgresql@10
    brew install postgresql
    brew install libpq
    echo 'export PATH="/usr/local/opt/libpq/bin:$PATH"' >> ~/.bash_profile
else
    sudo apt-get install postgresql-9.3 postgresql-contrib-9.3
    sudo apt-get install postgresql-9.4 postgresql-contrib-9.4
    sudo apt-get install postgresql-9.5 postgresql-contrib-9.5
    sudo apt-get install postgresql-9.6 postgresql-contrib-9.6
fi

