#!/bin/bash
mkdir -p .private .db .crl csr .certs certs
chmod 700 .private

cp /dev/null .db/ca.db
cp /dev/null .db/ca.db.attr

echo 40 > .db/ca.crt.srl
echo 40 > .db/ca.crl.srl

# Requesting Intermediate CA using etc/ca.conf
# Outputting --> ca.csr (Certificate Signing Request), ca.key (private key)
# -nodes to disable pass-phrase
openssl req -new -nodes \
    -config etc/ca.conf \
    -out csr/ca.csr \
    -keyout .private/ca.key

# After this you should manually sign the CSR to the Root-CA located

rm ./init